### ISSUE TITLE
Make a report of people that leave their group rooms

### ISSUE THREAD

**Issue by ShinzenATT** [Tolfx/DiscordGroupRandomizer#19]

**Comment by Tolfx** [comment]
Is possible if you catch the error. Since once we move all of the members, but one member is not there we will get an error, so if we make `reject` when `moveMembers` is undefined, we can later catch it.
https://github.com/Tolfx/DiscordGroupRandomizer/blob/54eb7db2d4ea55a0fa1d39da6a94da3125e5af16/lib/manageMembers.js#L23

When it gives out a error, we catch it in here:
https://github.com/Tolfx/DiscordGroupRandomizer/blob/54eb7db2d4ea55a0fa1d39da6a94da3125e5af16/commands/command/gather.js#L16

Once we catched it we can decide who it was and have a array that sorts all of the ID's whom was not there.
